spring:
  application:
    name: NoCheatCode

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000 # 60 seconds timeout
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1200000 # 20 minutes
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24 hours in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# AI Helper Configuration
ai:
  gemini:
    api:
      url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
      key: ${AI_GEMINI_API_KEY}

# Judge0 Configuration
judge0:
  api:
    key: ${JUDGE0_API_KEY}


